---

- name: Install NGINX on EC2
  apt:
    name: nginx
    state: present
  tags:
    - ec2

- name: Start NGINX service
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - ec2